### ISSUE TITLE
Extractor dependency missing

### ISSUE THREAD

**Issue by pasqLisena** [music-x-lab/SeqAttn#1]
Hello,
we are trying to run your code.

In your script, you import a `extractors` library:
https://github.com/music-x-lab/SeqAttn/blob/283368cc590f836a38f21002798b96cf618a371a/seq_attention_bidirectional_model_generation.py#L7

However, this library is not installed with `requirements.txt`, and we have not found it anywhere.

Can you please tell us how to install it? // cc @vincenzomadaghiele

**Comment by instr3** [comment]
Thanks for the issue. It should have been fixed in the new commit.
